version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_user_db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: users_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_user_data:/var/lib/mysql

  user-service:
    build: .
    container_name: user_service
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - mysql

volumes:
  mysql_user_data:
